version: "3.5"

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build: ./Frontend/Tumultu
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend/Tumultu:/usr/src/app
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
