version: '3'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build: ./Frontend/Tumultu
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend/Tumultu:/app`
    command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

volumes:
  app:
    external: true
